version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      editor:
        patterns: ['@codemirror/*', '@lezer/*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
