import { icon } from './icons';
import { examples, modeNames } from './examples';
export const shell = `
<a class="skip-link" href="#source-anchor">Skip to editor</a>
<header class="topbar"><a class="brand" href="https://vrrdnt.dev" aria-label="vrrdnt.dev home"><span class="brand-mark">${icon('format')}</span>vrrdnt.dev</a><span class="breadcrumb">/ <span>powerfx</span></span><nav aria-label="Site"><a class="source-link" href="https://github.com/vrrdnt/powerfx" target="_blank" rel="noreferrer">Source <span>↗</span></a><button class="icon-button" id="help" aria-label="Help and keyboard shortcuts">${icon('help')}</button><button class="icon-button" id="theme" aria-label="Switch color theme">${icon('sun')}</button></nav></header>
<main><section class="intro" aria-labelledby="title"><div><div class="eyebrow">THE WORKBENCH <span>/ 01</span></div><h1 id="title">Power Fx <span>& Flow</span><span class="title-cursor" aria-hidden="true">_</span></h1></div><div class="local-note"><span class="local-symbol" aria-hidden="true">◈</span><div>Local by design.<small>Your formulas stay in this browser.</small></div></div></section>
<section class="tool" aria-label="Formula formatter">
<div class="toolbar"><label class="select-field"><span>LANGUAGE</span><select id="mode" aria-label="Language">${Object.entries(
  modeNames,
)
  .map(([value, label]) => `<option value="${value}">${label}</option>`)
  .join(
    '',
  )}</select></label><div class="toolbar-divider"></div><label class="select-field preset-field"><span>LAYOUT</span><select id="preset" aria-label="Layout preset"><option value="adaptive">Adaptive</option><option value="expanded">Expanded</option><option value="compact">Compact</option><option value="custom">Custom</option></select></label><button id="settings" class="quiet-button" aria-label="Formatting settings">${icon('settings')}<span>Settings</span></button><div class="toolbar-actions"><button id="format" class="secondary-button">${icon('format')}Format <kbd>⌘ / Ctrl ↵</kbd></button><button id="copy" class="primary-button" disabled>${icon('copy')}Copy output</button></div></div>
<div id="suggestion" class="suggestion" hidden><span></span><button type="button"></button><button class="dismiss-suggestion" aria-label="Dismiss language suggestion">×</button></div>
<div class="pane-headers"><div class="pane-heading source-heading"><span class="pane-number">01</span><button class="pane-tab" id="source-tab" aria-pressed="true">Source</button><span id="source-badge" class="badge">EXAMPLE</span><div class="pane-actions"><button id="examples" class="text-button">Examples <span>⌄</span></button><button id="import" class="icon-button small" aria-label="Import a text or YAML file">${icon('upload')}</button><button id="clear" class="text-button">Clear</button></div></div><div class="pane-heading output-heading"><span class="pane-number">02</span><button class="pane-tab" id="output-tab" aria-pressed="false">Formatted</button><span id="ready-badge" class="badge status-badge">WAITING</span><div class="pane-actions"><button id="diff" class="text-button" aria-pressed="false">Diff</button><button id="focus" class="text-button" aria-pressed="false">Focus</button><button id="download" class="icon-button small" disabled aria-label="Download formatted file">${icon('download')}</button></div></div></div>
<div class="editor-area" id="source-anchor" tabindex="-1"><aside id="outline" aria-label="YAML properties" hidden><div class="outline-title">PROPERTIES</div><div id="outline-items"></div></aside><div id="editors"></div><div id="splitter" role="separator" aria-label="Resize editors" aria-orientation="vertical" aria-valuemin="25" aria-valuemax="75" aria-valuenow="50" tabindex="0"></div><div class="empty-hint" id="empty-hint" hidden><span>${icon('file')}</span><p>Give your formula some room.</p><small>Paste code, import a file, or try an example.</small></div></div>
<div class="statusbar"><span id="status" role="status">Starting formatter…</span><button id="cancel" class="text-button" hidden>Cancel</button><span class="status-spacer"></span><span id="stats">0 lines</span><span class="status-divider">/</span><span id="timing">—</span><span class="status-divider">/</span><span id="style-status">4 spaces · 100 cols</span></div><div id="diagnostics" class="diagnostics" hidden aria-label="Syntax diagnostics"></div></section>
<footer class="footer"><span><span class="keyboard-hint">↵</span> <kbd>Ctrl / ⌘ Enter</kbd> to format <span class="footer-divider">·</span> <kbd>Ctrl / ⌘ F</kbd> to find</span><span>Same formula. A clearer view.<span class="footer-mark">[ fx ]</span></span></footer></main>
<input id="file-input" type="file" accept=".txt,.fx,.powerfx,.yaml,.yml,.pa.yaml" hidden /><div id="toast" role="status" hidden></div>
<dialog id="settings-dialog" class="settings-dialog"><form method="dialog" class="dialog-header"><div><div class="eyebrow">MAKE IT YOURS</div><h2>Formatting settings</h2></div><button class="icon-button" aria-label="Close settings">${icon('close')}</button></form><div class="settings-content">
<fieldset><legend>Whitespace</legend><div class="setting-grid"><label>Indent size<select id="indent-size"><option value="2">2 spaces</option><option value="4">4 spaces</option><option value="8">8 spaces</option></select></label><label>Line width<input id="print-width" type="number" min="40" max="240" step="10" /></label></div><label class="check-row"><input id="tabs" type="checkbox" />Indent with tabs</label><label class="check-row"><input id="blank-lines" type="checkbox" />Preserve a blank line between sections</label></fieldset>
<fieldset><legend>Custom layout</legend><p class="setting-description">Changing these switches the layout to Custom.</p><div class="setting-grid"><label>Function arguments<select id="argument-layout"><option value="auto">Fit to line width</option><option value="expanded">One per line</option></select></label><label>Record fields<select id="record-layout"><option value="auto">Fit to line width</option><option value="expanded">One per line</option></select></label></div></fieldset>
<fieldset><legend>Language</legend><label>Power Fx separators<select id="locale"><option value="dot">Decimal dot · arguments , · actions ;</option><option value="comma">Decimal comma · arguments ; · actions ;;</option></select></label><p class="setting-description" id="locale-note">Use the convention your formula was written in. Formatting does not convert locales.</p></fieldset>
<fieldset><legend>Editor</legend><label class="check-row"><input id="live" type="checkbox" />Update the preview as I type</label><label class="check-row"><input id="wrap" type="checkbox" />Wrap long lines in the editor</label><label>Color theme<select id="theme-select"><option value="dark">Dark</option><option value="light">Light</option><option value="system">Use system theme</option></select></label></fieldset>
<fieldset><legend>Local storage</legend><label class="check-row"><input id="remember" type="checkbox" />Remember my code on this device</label><p class="setting-description">Off by default. Settings are saved locally; code is saved only when enabled. Nothing is uploaded.</p><button id="erase" class="danger-button" type="button">Erase saved code and settings</button></fieldset></div><div class="dialog-footer"><span>Changes update the preview.</span><button class="secondary-button" id="settings-done">Done</button></div></dialog>
<dialog id="examples-dialog" class="examples-dialog"><form method="dialog" class="dialog-header"><div><div class="eyebrow">START SOMEWHERE</div><h2>Try an example</h2></div><button class="icon-button" aria-label="Close examples">${icon('close')}</button></form><div class="examples-list">${examples.map((example, i) => `<button data-example="${i}"><span class="example-index">0${i + 1}</span><span><strong>${example.name}</strong><small>${modeNames[example.mode]}</small></span>${icon('arrow')}</button>`).join('')}</div><p class="dialog-note">Loading an example replaces the editor. Undo restores your previous code.</p></dialog>
<dialog id="help-dialog" class="help-dialog"><form method="dialog" class="dialog-header"><div><div class="eyebrow">A QUICK REFERENCE</div><h2>Four modes. One workspace.</h2></div><button class="icon-button" aria-label="Close help">${icon('close')}</button></form><div class="help-content"><dl><dt>Power Apps</dt><dd>Property formulas, actions, named formulas, user-defined functions and types. Select the matching decimal convention in Settings.</dd><dt>Power Apps YAML</dt><dd>Paste control code or import a .pa.yaml file. Formula properties are formatted; surrounding values and structure are preserved. Power Apps source uses invariant decimal-dot syntax.</dd><dt>Power Automate Cloud</dt><dd>Workflow expressions such as <code>if(equals(...),...)</code>, leading <code>@</code> expressions, and <code>@{…}</code> in text. This is a different language from Power Fx.</dd><dt>Power Automate Desktop</dt><dd>Power Fx expressions beginning with <code>=</code> and text containing <code>\${…}</code>. Plain desktop text is left as written.</dd></dl><h3>Choose your layout</h3><p><b>Adaptive</b> expands nested branching functions for readability. <b>Expanded</b> places arguments and fields on separate lines. <b>Compact</b> fits expressions within your line width. <b>Custom</b> uses your wrapping preferences.</p><h3>Safe to copy back?</h3><p>The formatter checks syntax and preserves formula tokens. It does not run code, check app bindings, or guarantee a function is available in your host. Control YAML can be pasted into Studio. External .pa.yaml editing belongs in Power Platform Git integration; editing an extracted .msapp file alone does not update an app.</p><h3>Keyboard</h3><p>Ctrl / ⌘ Enter: format · Ctrl / ⌘ F: find · Ctrl / ⌘ Z: undo · Escape: close a dialog. Tab indents inside the editor; press Escape, then Tab to move focus out.</p><p class="help-links"><a href="https://learn.microsoft.com/en-us/power-platform/power-fx/expression-grammar" target="_blank" rel="noreferrer">Power Fx grammar ↗</a><a href="https://github.com/vrrdnt/powerfx/issues" target="_blank" rel="noreferrer">Report an issue ↗</a></p><small>All formatting runs on your device. No analytics, accounts, or formula uploads.</small></div></dialog>`;
